[preface]
== Acknowledgments

Lots of people to thank, without whom this book would never have happened,
and/or would have been even worse than it is.

Thanks first to "Greg" at $OTHER_PUBLISHER, who was the first person to
encourage me to believe it really could be done. Even though your employers
turned out to have overly regressive views on copyright, I'm forever grateful
that you believed in me.

Thanks to Michael Foord, another ex-employee of Resolver Systems, for providing
the original inspiration by writing a book himself, and thanks for his ongoing
support for the project.  Thanks also to my boss Giles Thomas, for foolishly
allowing another one of his employees to write a book (although I believe he's
now changed the standard employment contract to say "no books").  Thanks also
for your ongoing wisdom and for setting me off on the testing path.

Thanks to my other colleagues, Glenn Jones and Hansel Dunlop, for being 
invaluable sounding boards, and for your patience with my one-track record 
conversation over the last year.

Thanks to my wife Clementine, and to both my families, without whose support
and patience I would never have made it.  I apologise for all the time spent
with nose in computer on what should have been memorable family occasions. I
had no idea when I set out what the book would do to my life ("Write it in my
spare time, you say?  That sounds reasonable...").  I couldn't have done it
without you.

Thanks to my tech reviewers, Jonathan Hartley, Nicholas Tollervey, and Emily
Bache, for your encouragements and invaluable feedback.   Especially Emily,
who actually conscientiously read every single chapter.  Partial credit
to Nick and Jon, but that should still be read as eternal gratitude. Having
y'all around made the whole thing less of a lonely endeavour. Without all of
you the book would have been little more than the nonsensical ramblings of an
idiot.

Thanks to everyone else who's given up some of their time to give some
feedback on the book, out of nothing more than the goodness of their heart:
Gary Bernhardt, Mark Lavin, Matt O'Donnell, Michael Foord, Hynek Schlawack,
Russell Keith-Magee, Andrew Godwin, Kenneth Reitz, and Nathan Stocks.  Thanks
for being much smarter than I am, and for preventing me from saying several
stupid things.  Naturally, there are still plenty of stupid things left in the
book, for which y'all can absolutely not be held responsible.

Thanks to my editor Meghan Blanchette, for being a very friendly and likeable
slave driver, and for keeping the book on track, both in terms of timescales
and by restraining my sillier ideas.  Thanks to all the others at
O'Reilly for your help, including Sarah Schneider, Kara Ebrahim, and 
Dan Fauxsmith for letting me keep British English. Thanks to Charles
Roumeliotis for your help with style and grammar.  We may never see eye-to-eye
on the merits of Chicago School quotation/punctuation rules, but I sure am
glad you were around.  And thanks to the design department for giving us a goat
for the cover!

And thanks most especially to all my Early Release readers, for all your help
picking out typos, for your feedback and suggestions, for all the ways in
which you helped to smooth out the learning curve in the book, and most of
all for your kind words of encouragement and support that kept me going.
Thank you Jason Wirth, Dave Pawson, Jeff Orr, Kevin De Baere, crainbf,
dsisson, Galeran, Michael Allan, James O'Donnell, Marek Turnovec, SoonerBourne,
julz, Cody Farmer, William Vincent, Trey Hunner, David Souther, Tom Perkin,
Sorcha Bowler, Jon Poler, Charles Quast, Siddhartha Naithani, Steve Young,
Roger Camargo, Wesley Hansen, Johansen Christian Vermeer, Ian Laurain, Sean
Robertson, Hari Jayaram, Bayard Randel, Konrad Korżel, Matthew Waller, Julian
Harley, Barry McClendon, Simon Jakobi, Angelo Cordon, Jyrki Kajala, Manish
Jain, Mahadevan Sreenivasan, Konrad Korżel, Deric Crago, Cosmo Smith, Markus
Kemmerling, Andrea Costantini, Daniel Patrick, Ryan Allen, Jason Selby, Greg
Vaughan, Jonathan Sundqvist, Richard Bailey, Diane Soini, Dale Stewart, Mark
Keaton, Johan Wärlander, Simon Scarfe, Eric Grannan, Marc-Anthony Taylor,
Maria McKinley, John McKenna, Rafał Szymański, Roel van der Goot, 
Ignacio Reguero, TJ Tolton, Jonathan Means, Theodor Nolte, Jungsoo Moon,
Craig Cook, Gabriel Ewilazarus, Vincenzo Pandolfo, David "farbish2", Nico
Coetzee, Daniel Gonzalez, Jared Contrascere, Zhao 赵亮,
and many, many more. If I've missed your name, you have an absolute right to be
aggrieved; I am incredibly grateful to you too, so write to me and I will try
and make it up to you in any way I can.

And finally thanks to you, the latest reader, for deciding to check out
the book!  I hope you enjoy it.

=== Additional Thanks for the Second Edition

Thanks to my wonderful editor for the second edition, Nan Barber, and to
Susan Conant, Kristen Brown, and the whole team at O'Reilly.
Thanks once again to Emily and Jonathan for tech reviewing, as well as to
Edward Wong for his very thorough notes.  Any remaining errors and
inadequacies are all my own.

Thanks also to the readers of the free edition who contributed comments,
suggestions, and even some pull requests. I have definitely missed some of
you on this list,  so apologies if your name isn't here, but thanks to Emre
Gonulates, Jésus Gómez, Jordon Birk, James Evans, Iain Houston, Jason DeWitt,
Ronnie Raney, Spencer Ogden, Suresh Nimbalkar, Darius, Caco,
LeBodro, Jeff, Duncan Betts, wasabigeek, joegnis, Lars, Mustafa, Jared, Craig,
Sorcha, TJ, Ignacio, Roel, Justyna, Nathan, Andrea, Alexandr, bilyanhadzhi,
mosegontar, sfarzy, henziger, hunterji, das-g, juanriaza, GeoWill, Windsooon,
gonulate, Margie Roswell, Ben Elliott, Ramsay Mayka, peterj, 1hx, Wi, Duncan
Betts, Matthew Senko, Neric "Kasu" Kaz, Dominic Scotto, Andrey Makarov,
and many, many more.

=== Additional Thanks for the Third Edition

Thanks to my editor Rita Fernando,
thanks to my tech reviewers Csanad, David, Sebastian and Jan,
and thanks to all the Early Release readers for your feedback,
big and small, including
Jonathan H,
James Evans,
Patrick Cantwell,
Devin Schumacher,
Nick Nielsen,
Teemu Viikeri,
Andrew Zipperer,
artGonza,
Joy Denebeim,
mshob23,
Romilly Cocking,
Zachary Kerbo,
Stephanie Goulet,
David Carter,
Jim Win Man,
and to anyone I've missed off this list,
my sincere apologies, and thank you thank you once again.

