[preface]
== Acknowledgments

Lots of people to thank, without whom this book would never have happened,
and/or would have been even worse than it is.

Thanks to "Greg" at $OTHER_PUBLISHER, who was the first person to encourage
me to believe it really could be done. Even though your employers turned 
out to have overly regressive views on copyright, I'm forever grateful that you
believed in me.

Thanks to Michael Foord, another ex-employee of Resolver Systems, for providing
the original insipiration by writing a book, and thanks for his ongoing support
for the project.  Thanks also to my boss Giles Thomas, for foolishly allowing
another one of his employees to write a book (although I believe he's now changed
the standard employment contract to say "no books").  Thanks also for your
ongoing wisdom and for setting me off on the testing path.

Thanks to my other colleagues, Glenn Jones and Hansel Dunlop, for being 
invaluable sounding boards, and your patience with my one-track record 
conversation over the last year.

Thanks to my wife Clementine, and to both my families, without whose support and
patience I would never have made it.  I apologise for all the time spent
with nose in computer on what should have been memorable family occasions.
I had no idea when I set out what the book would do to my life ("write it in 
my spare time you say?  That sounds reasonable...").  I couldn't have done it
without you.

Thanks to my tech reviewers, Jonathan Hartley, Nicholas Tollervey, and Emily
Bache, for your encouragements and invaluable feedback.   Especially Emily,
who actually conscientiously read every single chapter.  Partial credit
to Nick and Jon, but that should still be read as eternal gratitude. 
Without all of you the book would have been little more than the nonsensical
ramblings of an idiot.

Thanks to everyone else that's given up some of their time to give some
feedback on the book, out of nothing more than the goodness of their heart:
Mark Lavin, Gary Bernhardt, Matt O'Donnell, Michael Foord, Hynek Schlawack,
Russell Keith-Magee, Andrew Godwin and Kenneth Reitz.

Thanks to my editor Meghan Blanchette, for being a very friendly and likeable
slave driver, for keeping the book on track, both in terms of timescales and
by restraining my more silly content ideas.  Thanks to all the others at
O'Reilly for your help, including Sarah Schneider and Kara Ebrahim, and 
Dan Fauxsmith for letting me keep British English. Thanks to Charles
Roumeliotis for your help with style and grammar.  We may never see eye-to-eye
on Chichago School quotation/punctuation rules, but I sure am glad you were
around.  Thanks to the design department for giving us a goat for the cover!

But thanks most especially to all my Early Release readers, for all your help
picking out typos, for your feedback and suggestions, for all the ways in
which you helped to smooth out the learning curve in the book, and most of
all for your kind words of encouragement and support that kept me going.
Thanks you Jason Wirth, Dave Pawson, Jeff Orr, Kevin De Baere, crainbf,
dsisson, Galeran, Michael Allan, James O'Donnell, Marek Turnovec, SoonerBourne,
julz, Cody Farmer, William Vincent, Trey Hunner, David Souther, Tom Perkin,
Sorcha Bowler, Jon Poler, Charles Quast, Siddhartha Naithani, Steve Young,
Roger Camargo, Wesley Hansen, Johansen Christian Vermeer, Ian Laurain, Sean
Robertson, Hari Jayaram, Bayard Randel, Konrad Korżel, Matthew Waller, Julian
Harley, Barry McLendon, Simon Jakobi, Angelo Cordon, Jyrki Kajala, Manish Jain,
Mahadevan Sreenivasan, Konrad Korżel, Deric Crago, Cosmo Smith, Markus
Kemmerling, Andrea Costantini, Daniel Patrick, Ryan Allen, Jason Selby, Greg
Vaughan, Jonathan Sundqvist, Richard Bailey, Diane Soini, Dale Stewart, Mark
Keaton, Johan Wärlander, Simon Scarfe, Eric Grannan, Marc-Anthony Taylor,
Maria McKinley, and many, many more. If I've missed your name out, you have
an absolute right to be aggrieved, I am incredibly grateful to you too, 
write to me and I will try and make it up to you in any way I can.

And thanks to you, the latest reader!  I hope you enjoy it.

