[[appendix_tradeoffs]]
[appendix]
== Testing Tradeoffs: Choosing the Right Place to Test From

pick up in chapter 16, refactor form, move html back to template

tests were in the wrong place, better to have them in test_views.py

mind you, it's also tested in the FT.

-> 3 places we could/do test.

discuss contract between FE and BE.  it's the `name=` basically

where do we want to keep the logic about bootstrap css?

* show moving tests from test_forms.py to test_views.py
* get rid of assertions about `isinstance(... Form)`


lesson:  tests at higher level enable more refactoring


=== Deleting some FTs

validation test is doing quite a lot of work, tests integration w/ backend and bootstrap, good
main todos test is the key smoke test
test multiple lists?  less wortwhile.
test list sharing?  maybe not worth it.
test login? maybe not adding value


=== FT speedup techniques

`with self.subTest`.


=== Testing at a Lower Level

imagine a new feature, "strict todos":

- rule about duplicate items is relaxed for non-strict todos
- strict todos must start with capital letter and end with full stop
- use linguistic analysis to check for imperative mood (?)

=> justitify some proper unit tests?

at the very least, testing for the regex _could_ happen at a lower level

