Containerization
~~~~~~~~~~~~~~~~

TODO: Explain virtualization (vagrant) vs containerization (docker)
TODO: Explain images -> containers


Installing docker
~~~~~~~~~~~~~~~~~

Move everything in the _python-tdd-book_ directory in a new directory, except for the `.git`, `.gitignore` and the new directory itself. I'm going to name this new directory _src_.

[subs=quotes]
.on Windows:
?? TODO

[subs=quotes]
.on Mac/Linux:
----
$ *cd python-tdd-book*
$ *mkdir src*
$ *mv !(.git|.gitignore|src) src/*
----

Docker security
~~~~~~~~~~~~~~~

Concept of least privileges.

TODO securing the host OS


Protecting the docker daemon
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

TODO: confirm this is done automatically on Mac and Windows.

You don't want to run Docker as a privileged user.

- $ sudo groupadd docker
- $ sudo usermod -aG docker $USER
- you may need to reboot your computer for it to take effect, but sometimes a logout/login is enough


Protecting the container
~~~~~~~~~~~~~~~~~~~~~~~~

- user mapping
- run container as non-root user
- disable root login on container


why it's beneficial to choose the smallest effective images:
  - from performance POV
  - from the attack surface POV
  - it's ok to play around in a more equipped base image, but deploy on :alpine


sources:

https://docs.docker.com/engine/security/
https://github.com/OWASP/Docker-Security
https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html
