[[chapter-3]]
Testing a Simple Home Page with Unit Tests
------------------------------------------


((("unit tests", "for simple home page", id="ix_ch03-asciidoc0", range="startofrange")))
We finished the last chapter with a functional test failing, telling us that it
wanted the home page for our site to have ``To-Do'' in its title. It's time to
start working on our application.

.Warning: Things Are About to Get Real
*******************************************************************************
The first two chapters were intentionally nice and light.  From now on, we
get into some more meaty coding.  Here's a prediction:  at some point, things
are going to go wrong.  You're going to see different results from what I say
you should see. This is a Good Thing, because it will be a genuine
character-building Learning Experience(TM). 

One possibility is that I've given some ambiguous explanations, and you've
done something different from what I intended. Step back and have a think about
what we're trying to achieve at this point in the book. Which file are we
editing, what do we want the user to be able to do, what are we testing and
why?  It may be that you've edited the wrong file or function, or are running
the wrong tests.  I reckon you'll learn more about TDD from these stop and think
moments than you do from all the bits where the following instructions and
copy-pasting goes smoothly.
((("debugging")))

Or it may be a real bug. Be tenacious, read the error message carefully (see
my aside on reading tracebacks a little later on in the chapter), and
you'll get to the bottom of it. It's probably just a missing comma, or
trailing-slash, or maybe a missing "s" in one of the Selenium find methods.
But, as <<lpthw,Zed Shaw put it so well>>, this kind of debugging is also an
absolutely vital part of learning, so do stick it out!

You can always drop me an email (or try the
https://groups.google.com/forum/#!forum/obey-the-testing-goat-book[Google
Group]) if you get really stuck.  Happy debugging!
*******************************************************************************



Our First Django App, and Our First Unit Test
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

((("Django", "apps")))
Django encourages you to structure your code into 'apps': the theory is that
one project can have many apps, you can use third-party apps developed by other
people, and you might even reuse one of your own apps in a different
project ... although I admit I've never actually managed it myself!  Still, apps
are a good way to keep your code organised.

Let's start an app for our to-do lists:

[subs="specialcharacters,quotes"]
----
$ *python3 manage.py startapp lists*
----

That will create a folder at 'superlists/lists', next to
'superlists/superlists', and within it a number of placeholder files for
things like models, views, and, of immediate interest to us, tests:

----
superlists/
├── db.sqlite3
├── functional_tests.py
├── lists
│   ├── admin.py
│   ├── __init__.py
│   ├── migrations
│   │   └── __init__.py
│   ├── models.py
│   ├── tests.py
│   └── views.py
├── manage.py
└── superlists
    ├── __init__.py
    ├── __pycache__
    ├── settings.py
    ├── urls.py
    └── wsgi.py
----


Unit Tests, and How They Differ from Functional Tests
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

((("unit tests", "vs. functional tests (FT)", sortas="functionaltests")))
((("functional tests/testing (FT)", "vs. unit tests", sortas="unittests")))
As with so many of the labels we put on things, the line between unit tests and
functional tests can become a little blurry at times. The basic distinction,
though, is that functional tests test the application from the outside, from
the point of view of the user. Unit tests test the application from the
inside, from the point of view of the programmer.

The TDD approach I'm following wants our application to be covered by
both types of test. Our workflow will look a bit like this:

1.  We start by writing a 'functional test', describing the new functionality
    from the user's point of view.

2.  Once we have a functional test that fails, we start to think about how
    to write code that can get it to pass (or at least to get past its current
    failure). We now use one or more 'unit tests' to define how we want our
    code to behave--the idea is that each line of production code we write
    should be tested by (at least) one of our unit tests.

3.  Once we have a failing unit test, we write the smallest amount of
    'application code' we can, just enough to get the unit test to pass.
    We may iterate between steps 2 and 3 a few times, until we think the
    functional test will get a little further.

4.  Now we can rerun our functional tests and see if they pass, or get a
    little further.  That may prompt us to write some new unit tests, and
    some new code, and so on.

You can see that, all the way through, the functional tests are driving what 
development we do from a high level, while the unit tests drive what we do
at a low level.

Does that seem slightly redundant? Sometimes it can feel that way, but
functional tests and unit tests do really have very different objectives, and
they will usually end up looking quite different.  

NOTE: Functional tests should help you build an application with the right
functionality, and guarantee you never accidentally break it.  Unit tests
should help you to write code that's clean and bug free.

Enough theory for now, let's see how it looks in practice.


Unit Testing in Django
~~~~~~~~~~~~~~~~~~~~~~

((("unit tests", "in Django", sortas="django")))
((("Django", "unit testing in")))
Let's see how to write a unit test for our home page view. Open up the new
file at 'lists/tests.py', and you'll see something like this:

[role="sourcecode currentcontents"]
.lists/tests.py
[source,python]
----
from django.test import TestCase

# Create your tests here.
----

((("Django", "TestCase")))
Django has helpfully suggested we use a special version of `TestCase`, which
it provides. It's an augmented version of the standard `unittest.TestCase`,
with some additional Django-specific features, which we'll discover over the 
next few chapters.

You've already seen that the TDD cycle involves starting with a test that
fails, then writing code to get it to pass. Well, before we can even get that
far, we want to know that the unit test we're writing will definitely be
run by our automated test runner, whatever it is.  In the case of
'functional_tests.py', we're running it directly, but this file made by Django
is a bit more like magic. So, just to make sure, let's make a deliberately
silly failing test:

++++
<?hard-pagebreak?>
++++

[role="sourcecode"]
.lists/tests.py
[source,python]
----
from django.test import TestCase

class SmokeTest(TestCase):

    def test_bad_maths(self):
        self.assertEqual(1 + 1, 3)
----

((("manage.py")))
Now let's invoke this mysterious Django test runner. As usual, it's a
'manage.py' ||command:||


[subs="specialcharacters,macros"]
----
$ pass:quotes[*python3 manage.py test*]
Creating test database for alias 'default'...
F
======================================================================
FAIL: test_bad_maths (lists.tests.SmokeTest)
 ---------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/superlists/lists/tests.py", line 6, in test_bad_maths
    self.assertEqual(1 + 1, 3)
AssertionError: 2 != 3

 ---------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
Destroying test database for alias 'default'...
----

Excellent.  The machinery seems to be working. This is a good point for a
commit:


[subs="specialcharacters,quotes"]
----
$ *git status*  # should show you lists/ is untracked
$ *git add lists*
$ *git diff --staged*  # will show you the diff that you're about to commit
$ *git commit -m "Add app for lists, with deliberately failing unit test"*
----

((("commits")))
As you've no doubt guessed, the `-m` flag lets you pass in a commit message
at the command line, so you don't need to use an editor. It's up to you
to pick the way you like to use the Git command line, I'll just show you 
the main ones I've seen used.  The main rule is: 'make sure you always review
what you're about to commit before you do it'.


Django's MVC, URLs, and View Functions
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

((("Model-View-Controller (MVC)")))
((("Django", "Model-View-Controller (MVC)")))
((("MVC frameworks")))
Django is broadly structured along a classic 'Model-View-Controller'
(MVC) pattern.  Well, 'broadly'.  It definitely does have models, but its
views are more like a controller, and it's the templates that are actually the
view part, but the general idea is there.  If you're interested, you can
look up the finer points of the discussion
https://docs.djangoproject.com/en/1.8/faq/general/[in the Django FAQs].

((("view functions, in Django")))
((("URLs", "in Django", id="ix_ch03-asciidoc1", range="startofrange")))
((("Django", "URLs in", id="ix_ch03-asciidoc2", range="startofrange")))
((("Django", "view functions in")))
Irrespective of any of that, like any web server, Django's main job is to
decide what to do when a user asks for a particular URL on our site.
Django's workflow goes something like this:

1. An HTTP 'request' comes in for a particular 'URL'.
2. Django uses some rules to decide which 'view' function should deal with
  the request (this is referred to as 'resolving' the URL).
3. The view function processes the request and returns an HTTP 'response',
   usually containing some HTML to display in the users' browser.

We'll look at resolving later.  Let's start by testing whether we can 
build a view function that can produce the right kind of HTML


Open up 'lists/tests.py', and change our silly test to something like
this--I'll explain each step in turn:


[role="sourcecode"]
.lists/tests.py
[source,python]
----
from django.test import TestCase
from django.http import HttpRequest

from lists.views import home_page


class HomePageTest(TestCase):

    def test_home_page_returns_correct_html(self):
        request = HttpRequest()  #<1>
        response = home_page(request)  #<2>
        self.assertTrue(response.content.startswith(b'<html>'))  #<3>
        self.assertIn(b'<title>To-Do lists</title>', response.content)  #<4>
        self.assertTrue(response.content.endswith(b'</html>'))  #<3>
----

What's going on in this new test?  

<1> We create an `HttpRequest` object, which is what Django will see when
    a user's browser asks for a page.

<2> We pass it to our `home_page` view, which gives us a response. You won't be
    surprised to hear that this object is an instance of a class called
    `HttpResponse`.
    +
    Then, we assert that the `.content` of the response--which is the HTML
    that we send to the user--has certain properties. 

<3> We want it to start with an `<html>` tag which gets closed at the end.
    Notice that `response.content` is raw bytes, not a Python string, so we
    have to use the `b''` syntax to compare them. More info is available in
    Django's 
    https://docs.djangoproject.com/en/1.8/topics/python3/[Porting to Python 3
    docs].

<4> And we want a `<title>` tag somewhere in the middle, with the words
    "To-Do lists" in it--because that's what we specified in our functional
    test.

You can see that the unit test was driven by the functional test, but it's also
much closer to the actual code--we're thinking like programmers now.


So, what do you think will happen when we run the tests?


[subs="specialcharacters,macros"]
----
$ pass:quotes[*python3 manage.py test*]
Creating test database for alias 'default'...
E
======================================================================
ERROR: lists.tests (unittest.loader.ModuleImportFailure)
 ---------------------------------------------------------------------
Traceback (most recent call last):
[...]
  File "/workspace/superlists/lists/tests.py", line 4, in <module>
    from lists.views import home_page
ImportError: cannot import name 'home_page'


 ---------------------------------------------------------------------
Ran 1 test in 0.004s

FAILED (errors=1)

ImportError: cannot import name 'home_page'
----

It's a very predictable and uninteresting error: we tried to import something
we haven't even written yet. But it's still good news--for the purposes of
TDD, an exception which was predicted counts as an expected failure.
Since we have both a failing functional test and a failing unit test, we have
the Testing Goat's full blessing to code away.


At Last! We Actually Write Some Application Code!
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

It is exciting isn't it?  Be warned, TDD means that long periods of
anticipation are only defused very gradually, and by tiny increments.
Especially since we're learning and only just starting out, we only allow
ourselves to change (or add) one line of code at a time--and each time, we
make just the minimal change required to address the current test failure.

I'm being deliberately extreme here, but what's our current test failure? 
We can't import `home_page` from `lists.views`?  OK, let's fix that--and only
that.  In 'lists/views.py':

[role="sourcecode"]
.lists/views.py
[source,python]
----
from django.shortcuts import render

# Create your views here.
home_page = None
----

"'You must be joking!'" I can hear you say.  

I can hear you because it's what I used to say (with feeling) when
my colleagues first demonstrated TDD to me.  Well, bear with me, we'll talk
about whether or not this is all taking it too far in a little while.  For now,
let yourself follow along, even if it's with some exasperation, and see where
it takes us.


The Unit-Test/Code Cycle
^^^^^^^^^^^^^^^^^^^^^^^^

((("unit-test/code cycle", id="ix_ch03-asciidoc4", range="startofrange")))
We can start to settle into the TDD 'unit-test/code cycle' now:

1. In the terminal, run the unit tests and see how they fail.
2. In the editor, make a minimal code change to address the current test failure.

And repeat! 

The more nervous we are about getting our code right, the smaller and more
minimal we make each code change--the idea is to be absolutely sure that each
bit of code is justified by a test. It may seem laborious, but once you get 
into the swing of things, it really moves quite fast--so much so that,
at work, we usually keep our code changes microscopic even when we're
confident we could skip ahead.


Let's run the tests again:

----
TypeError: 'NoneType' object is not callable
----

OK, so let's make `home_page` into some kind of function.

[role="sourcecode"]
.lists/views.py
[source,python]
----
def home_page(request):
    pass
----


What's next? Running the unit tests again gives us:

----
TypeError: home_page() takes 0 positional arguments but 1 was given
----

Let's see how fast we can get this cycle going:

* Minimal code change:

[role="sourcecode"]
.lists/views.py
[source,python]
----
def home_page(request):
    pass
----

* Tests:

----
    self.assertTrue(response.content.startswith(b'<html>'))
AttributeError: 'NoneType' object has no attribute 'content'
----

* Code--we use `django.http.HttpResponse`, as predicted:

[role="sourcecode"]
.lists/views.py
[source,python]
----
from django.http import HttpResponse

def home_page(request):
    return HttpResponse()
----

* Tests again:

----
    self.assertTrue(response.content.startswith(b'<html>'))
AssertionError: False is not true
----

* Code again:

[role="sourcecode"]
.lists/views.py
[source,python]
----
def home_page(request):
    return HttpResponse('<html>')
----

* Tests:

----
AssertionError: b'<title>To-Do lists</title>' not found in b'<html>'
----

* Code:


[role="sourcecode"]
.lists/views.py
[source,python]
----
def home_page(request):
    return HttpResponse('<html><title>To-Do lists</title>')
----

* Tests--almost there?

----
    self.assertTrue(response.content.endswith(b'</html>'))
AssertionError: False is not true
----

* Come on, one last effort:


[role="sourcecode"]
.lists/views.py
[source,python]
----
def home_page(request):
    return HttpResponse('<html><title>To-Do lists</title></html>')
----


* Surely?



[subs="specialcharacters,macros"]
----
$ pass:quotes[*python3 manage.py test*]
Creating test database for alias 'default'...
.
 ---------------------------------------------------------------------
Ran 1 test in 0.003s

OK
Destroying test database for alias 'default'...
----

Hooray! Our first ever unit test pass!


Now, let's run our functional tests.  Don't forget to spin up the dev
server again, if it's not still running. It feels like the final heat
of the race here, surely this is it ... could it be?

----
FAIL: test_can_start_a_list_and_retrieve_it_later (__main__.NewVisitorTest)
 ---------------------------------------------------------------------
Traceback (most recent call last):
  File "functional_tests.py", line 19, in test_can_start_a_list_and_retrieve_it_later
    self.assertIn('To-Do', self.browser.title)
AssertionError: 'To-Do' not found in 'Welcome to Django'
----


nope.


this is why we need fts and unit tests


wire up urls.py  (yes, you could unit test this too. but we won't)

[role="sourcecode currentcontents"]
.superlists/urls.py
[source,python]
----
"""superlists URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
]
----

Let's follow those instructions.  We're using function-based views (because I still find class-based views a little weird.  Check out the appendix for more info)


[role="sourcecode"]
.lists/tests.py
[source,python]
----
from django.conf.urls import include, url
from django.contrib import admin

from lists import views

urlpatterns = [
    url(r'^$', views.home_page, name='home'),
    url(r'^admin/', include(admin.site.urls)),
]
----


and now run the Ft again:


[subs="specialcharacters,macros"]
----
$ pass:quotes[*python3 functional_tests.py*]
F
======================================================================
FAIL: test_can_start_a_list_and_retrieve_it_later (__main__.NewVisitorTest)
 ---------------------------------------------------------------------
Traceback (most recent call last):
  File "functional_tests.py", line 20, in
test_can_start_a_list_and_retrieve_it_later
    self.fail('Finish the test!')
AssertionError: Finish the test!

 ---------------------------------------------------------------------
Ran 1 test in 1.609s

FAILED (failures=1)
----

Failed? What? Oh, it's just our little reminder? Yes? Yes! We have a web page!

Ahem.  Well, 'I' thought it was a thrilling end to the chapter. You may still
be a little baffled, perhaps keen to hear a justification for all these tests,
and don't worry, all that will come, but I hope you felt just a tinge of
excitement near the end there.

Just a little commit to calm down, and reflect on what we've covered:




[subs="specialcharacters,quotes"]
----
$ *git diff*  # should show changes to tests.py, views.py and urls.py
$ *git commit -am "First unit test and view function"*
----

((("commits")))
That was the last variation on `git commit` I'll show, the `a` and `m` flags
together, which adds all changes to tracked files and uses the commit message
from the command line. 
(((range="endofrange", startref="ix_ch03-asciidoc1")))
(((range="endofrange", startref="ix_ch03-asciidoc2")))
(((range="endofrange", startref="ix_ch03-asciidoc3")))


WARNING: `git commit -am` is the quickest formulation, but also gives you the
    least feedback about what's being committed, so make sure you've done a
    `git status` and a `git diff` beforehand, and are clear on what changes are
    about to go in.


Let's recap on what we got up to

[subs="specialcharacters,quotes"]
----
$ *git log --oneline*
a6e6cc9 Basic view now returns minimal HTML
ea2b037 Add app for lists, with deliberately failing unit test
[...]
----

Not bad--we covered:

* Starting a Django app
* The Django unit test runner
* The difference between FTs and unit tests
* Django view functions, request and response objects
* Returning basic HTML
* And Django URL resolving in 'urls.py'
(((range="endofrange", startref="ix_ch03-asciidoc0")))
(((range="endofrange", startref="ix_ch03-asciidoc4")))

.Useful Commands and Concepts
*******************************************************************************
Running the Django dev server::
    *`python3 manage.py runserver`*

Running the functional tests::
    *`python3 functional_tests.py`*

Running the unit tests::
    *`python3 manage.py test`*

The unit-test/code cycle::
    1. Run the unit tests in the terminal.
    2. Make a minimal code change in the editor.
    3. Repeat!

*******************************************************************************

