[[part3]]
[part]
== More Advanced Topics in Testing

[partintro]
--

"Oh my gosh, what?  Another section?  Harry, I'm exhausted, it's already 
been three hundred pages, I don't think I can handle a whole &rsquo;nother section
of the book.  Particularly not if it's called 'Advanced&rsquo;...maybe I can
get away with just skipping it?"

Oh no, you can't! This may be called the advanced section, but it's full of
really important topics for TDD and web development.  No way can you skip
it. If anything, it's 'even more important' than the first two sections.

We'll be talking about how to integrate third-party systems, and how to test
them.  Modern web development is all about reusing existing components.  We'll
cover mocking and test isolation, which is really a core part of TDD, and a
technique you're going to need for all but the simplest of codebases. We'll
talk about server-side debugging, and test fixtures, and how to set up a
Continuous Integration environment.  None of these things are
take-it-or-leave-it optional luxury extras for your project--they're all
vital!


Inevitably, the learning curve does get a little steeper in this section. You
may find yourself having to read things a couple of times before they sink in,
or you may find that things don't work on the first go, and that you need to do a bit
of debugging on your own.  But persist with it!  The harder it is, the more
rewarding it is. And I'm always happy to help if you're stuck; just drop me
an email at obeythetestinggoat@gmail.com.

Come on; I promise the best is yet to come!
--
