[[part4]]
[part]
== More Advanced Topics in Testing

[partintro]
--

"Oh my gosh, what?  Another section?  Harry, I'm exhausted, it's already 
been three hundred pages, I don't think I can handle a whole &rsquo;nother section
of the book.  Particularly not if it's called 'Advanced&rsquo;...maybe I can
get away with just skipping it?"

Oh no, you can't! This may be called the advanced section,
but it's full of really important topics for TDD and web development.
No way can you skip it.
If anything, it's 'even more important' than the first two sections.

First off, we'll get into that _sine qua non_ of web development, JavaScript.
Seeing how TDD works in another language can give you a whole new perspective.

We'll be talking about a key technique, "spiking",
which is where you relax the strict rules of TDD,
and allow yourself a bit of exploratory hacking.

TIP: A common objection to TDD is "how can I write tests if I don't even know what I'm doing?"
  Spiking is the bit where you get to play around and figure things out,
  so you can come back and do it test-first later.

We'll be talking about how to integrate third-party systems,
and how to test them.
We'll cover mocking, which is a hard to avoid.footnote:[
Although not impossible!  Check out the book www.cosmicpython.com[Cosmic Python],
which has tips on testing without mocks.
I happen to know that at least one of the two authors is incredibly wise.]
in the world of Python testing.

We'll talk about server-side debugging, and test fixtures,
and how to set up a Continuous Integration environment.
None of these things are take-it-or-leave-it optional luxury extras for your project--they're all
vital!


Inevitably, the learning curve does get a little steeper in this section.
You may find yourself having to read things a couple of times before they sink in,
or you may find that things don't work on the first go,
and that you need to do a bit of debugging on your own.

But I encourage you to persist with it!
The harder it is, the more rewarding it is, right?
And, remember, I'm always happy to help if you're stuck;
just drop me an email at obeythetestinggoat@gmail.com.

Come on; I promise the best is yet to come!
--
