[[part1]]
[part]
[role="pagenumrestart"]
== The Basics of TDD and Django

[partintro]
--
In this first part, I'm going to introduce the basics of 'Test-Driven
Development' (TDD). We'll build a real web application from scratch, writing tests first at every stage.

We'll cover functional testing with Selenium, as well as unit testing,
and see the difference between the two.
I'll introduce the TDD workflow, Red/Green/Refactor.

I'll also be using a version control system (Git).
We'll discuss how and when to do commits and integrate them with the TDD and web development workflow.

We'll be using Django, the Python world's most popular web framework (probably).
I've tried to introduce the Django concepts slowly and one at a time,
and provide lots of links to further reading.
If you're a total beginner to Django, I thoroughly recommend taking the time to read them.
If you find yourself feeling a bit lost,
take a couple of hours to go through the https://docs.djangoproject.com/en/5.1/intro/[official Django tutorial]
and then come back to the book.

In Part 1 you'll also get to meet the Testing Goat...

.Be Careful with Copy and Paste
[TIP]
====
If you're working from a digital version of the book,
it's natural to want to copy and paste code listings from the book as you're working through it.
It's much better if you don't: typing things in by hand gets them into your muscle memory,
and just feels much more real.
You also inevitably make the occasional typo, and debugging them is an important thing to learn.

Quite apart from that, you'll find that the quirks of the PDF format
mean that weird stuff often happens when you try to copy/paste from it...
====

--
