[[part2]]
Web development 'sine qua non''s
================================

[partintro]
--
[quote, Jeff Atwood]
______________________________________________________________
Real developers ship.
______________________________________________________________

If this were just a guide to TDD in a normal programming field, we might be
able to congatulate ourselves about now. After all, we've got some solid basics
of TDD and Django under our belts, we've got all we need to start building
some quite complex sites.

But, real developers ship, and in order to ship, we're going to have to tackle
some of the trickier but unavoidable aspects of web development: static files,
form data validation, database migrations, the dreaded JavaScript, but most
hairy of all, deployment to a production server.

Still, at every stage, TDD can help us to get these things right too.

In this section, I'm still trying to keep the learning curve relatively
soft, but we will meet several major new concepts and technologies. I'll only
be able to dip lightly into each one -- I hope to demonstrate enough of each
to get you started when you get to your own project, but you will also find
yourself needing to do your own reading around when you start to apply these
topics to your own projects.
--
