[[part2]]
[part]
== Web Development 'Sine Qua Nons'

[partintro]
--
[quote, Jeff Atwood]
______________________________________________________________
Real developers ship.
______________________________________________________________

If this were just a guide to TDD in a normal programming field, we might be
able to congratulate ourselves about now. After all, we've got some solid
basics of TDD and Django under our belts; we've got all we need to start
building a website.

But, real developers ship, and in order to ship, we're going to have to tackle
some of the trickier but unavoidable aspects of web development: static files,
form data validation, the dreaded JavaScript, but most hairy of all, deployment
to a production server.

At every stage, TDD can help us to get these things right too.

In this section, I'm still trying to keep the learning curve relatively
soft, but we will meet several major new concepts and technologies. I'll only
be able to dip lightly into each one--I hope to demonstrate enough of each
to get you started when you get to your own project, but you will also need
to do your own reading around when you start to apply these topics in "real
life".

For example, if you weren't familiar with Django before starting on the book,
you may find that taking a little time to run through the 
https://docs.djangoproject.com/en/1.11/intro/tutorial01/#creating-models[official Django tutorial]
at this point would complement what you've learned so far nicely,
and will leave you more confident with the Django stuff over the next few
chapters, so you can focus on the core concepts.

////
IDEA:
TIP: I've heard from readers (especially those who had only just started
    learning web development), saying they got impatient at this point; they
    decided to stop reading for now, and went off to get their hands dirty by
    building a real app based on what they'd learned so far.  If that's you
    then great! Come back to this book in 6 months' time when you've earned a
    few bruises from the real world, and you'll probably get even more out of
    the rest of the book.
////

Oh, but there's lots of fun stuff coming up!  Just you wait!

--
