["dedication", role="praise"]
== Praise for 'Test-Driven Development with Python'

[quote, Michael Foord, Python Core Developer and Maintainer of unittest]
____
“In this book, Harry takes us on an adventure of discovery with Python and testing. It’s an excellent book, fun to read and full of vital information. It has my highest recommendations for anyone interested in testing with Python, learning Django or wanting to use Selenium. Testing is essential for developer sanity and it's a notoriously difficult field, full of trade-offs. Harry does a fantastic job of holding our attention whilst exploring real world testing practices.”
____

[quote, Kenneth Reitz, Fellow at Python Software Foundation]
____
“This book is far more than an introduction to Test Driven Development—it’s a complete best-practices crash course, from start to finish, into modern web application development with Python. Every web developer needs this book.” 
____

[quote, Daniel and Audrey Roy Greenfeld, authors of "Two Scoops of Django" (Two Scoops Press)]
____
“Harry’s book is what we wish existed when we were learning Django. At a pace that’s achievable and yet delightfully challenging, it provides excellent instruction for Django and various test practices. The material on Selenium alone makes the book worth purchasing, but there's so much more!”
____
