CHAPTERS = [
    # part 1
    "chapter_01",
    "chapter_02_unittest",
    "chapter_03_unit_test_first_view",
    "chapter_04_philosophy_and_refactoring",
    "chapter_05_post_and_database",
    "chapter_06_explicit_waits_1",
    "chapter_07_working_incrementally",
    # part 2
    "chapter_08_prettification",
    "chapter_09_docker",
    "chapter_11_ansible",
    "chapter_organising_test_files",
    "chapter_database_layer_validation",
    "chapter_simple_form",
    "chapter_advanced_forms",
    "chapter_javascript",
    "chapter_deploying_validation",
    # part 3
    "chapter_spiking_custom_auth",
    "chapter_mocking",
    "chapter_fixtures_and_wait_decorator",
    "chapter_server_side_debugging",
    "chapter_outside_in",
    "chapter_purist_unit_tests",
    "chapter_CI",
    "chapter_page_pattern",
    "chapter_hot_lava",
]
