#!/usr/bin/env python3
import unittest

from book_tester import ChapterTest


class Chapter24Test(ChapterTest):
    chapter_name = "chapter_24_outside_in"
    previous_chapter = "chapter_23_debugging_prod"

    def test_listings_and_commands_and_output(self):
        self.parse_listings()
        # self.prep_virtualenv()

        # sanity checks
        self.assertEqual(self.listings[0].type, "code listing with git ref")
        self.assertEqual(self.listings[1].type, "code listing with git ref")

        # skips
        # self.skip_with_check(22, 'switch back to master') # comment

        self.start_with_checkout()
        self.prep_database()

        # hack fast-forward
        self.skip_forward_if_skipto_set()

        while self.pos < len(self.listings):
            print(self.pos, self.listings[self.pos].type)
            self.recognise_listing_and_process_it()

        self.assert_all_listings_checked(self.listings)
        self.check_final_diff(ignore=["moves", "Generated by Django 5"])


if __name__ == "__main__":
    unittest.main()
