#!/usr/bin/env python3
import os
import unittest

from book_tester import (
    ChapterTest,
    Command,
)


class Chapter7Test(ChapterTest):
    chapter_name = "chapter_07_working_incrementally"
    previous_chapter = "chapter_06_explicit_waits_1"

    def test_listings_and_commands_and_output(self):
        self.parse_listings()

        # sanity checks
        self.assertEqual(self.listings[0].type, "output")
        self.assertEqual(self.listings[1].type, "output")

        # skips
        self.skip_with_check(57, "should show 4 changed files")  # git
        self.skip_with_check(62, "add a message summarising")  # git
        self.skip_with_check(79, "5 changed files")  # git
        self.skip_with_check(81, "forms x2")  # git
        self.skip_with_check(108, "3 changed files")  # git

        # other prep
        self.start_with_checkout()
        self.run_command(Command("python3 manage.py migrate --noinput"))

        # hack fast-forward
        self.skip_forward_if_skipto_set()

        while self.pos < len(self.listings):
            print(self.pos)
            self.recognise_listing_and_process_it()

        self.check_final_diff(ignore=["moves", "Generated by Django 5."])
        self.assert_all_listings_checked(self.listings)


if __name__ == "__main__":
    unittest.main()
