#!/usr/bin/env python3
import os
import unittest

from book_tester import ChapterTest


class Chapter16Test(ChapterTest):
    chapter_name = "chapter_16_advanced_forms"
    previous_chapter = "chapter_15_simple_form"

    def test_listings_and_commands_and_output(self):
        self.parse_listings()

        # sanity checks
        self.assertEqual(self.listings[0].type, "code listing with git ref")
        self.assertEqual(self.listings[1].type, "test")
        self.assertEqual(self.listings[2].type, "output")

        # prep
        self.start_with_checkout()
        self.prep_database()

        # skips
        self.skip_with_check(28, "# should show changes")  # diff

        # hack fast-forward
        if os.environ.get("SKIP"):
            self.pos = 60
            self.sourcetree.run_command(
                "git switch {}".format(self.sourcetree.get_commit_spec("ch15l020"))
            )

        while self.pos < len(self.listings):
            print(self.pos, self.listings[self.pos].type)
            self.recognise_listing_and_process_it()

        self.assert_all_listings_checked(self.listings)
        self.check_final_diff(ignore=["Generated by Django 5."])


if __name__ == "__main__":
    unittest.main()
