Chapter 1 - Getting Django set up using a Functional Test
---------------------------------------------------------

In my first draft of this book, I started off with a "toy" example, designed to
introduce the concepts of TDD before we dive into the complexities of web 
development (you can still look it up, if you like, it's on my github page).

In the end though, I decided that you guys would prefer to dive right in.
You're here to learn about web programming, not Roman Numeral calculators
(even if the latter can be surprisingly interesting).

So without further ado, let's get started.

Our first Selenium test - open a web browser to check Django works
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The first step in web development is usually getting your web framework
installed and configured. But in TDD, the first step is always the same: *write
a test*.  Once we've written the test, we run it and check that it fails as
expected.  Only then do we go ahead and write production code.

We start with nice small steps, so the first thing we want to do is check that
we've installed Django successfully, and that we spin up a development server
and take a look at our website using a web browser.

We'll use the Selenium browser automation tool for this. Create a new Python
file called `tests.py`, and write the following code.
